    var arrayKino = [
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=1",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Sonic the Hedgehog 2",
          "img": "https://picsum.photos/200/300?random=2",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Halo",
          "img": "https://picsum.photos/200/300?random=3",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Message Trailer",
          "img": "https://picsum.photos/200/300?random=4",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=5",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=6",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=7",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=8",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=9",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=10",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=11",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=12",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=13",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=14",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=15",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=16",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=17",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=18",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=19",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },
        {
          "id": 1,
          "name": "Tinch Okean Daxshatlari",
          "img": "https://picsum.photos/200/300?random=20",
          "youtubeId": "Id here",
          "title": "title here",
          "Gendre": "Sciens Fiction",
        },

    ]
    var elp = document.querySelector('.content-info');
	var poklenght = arrayKino.length;
	let text = "<ol>";
	for (let i= 0; i < arrayKino.length; i++){
		text += '<li>' + arrayKino[i].name;
	}
	text += "</ul>";
	
	document.querySelector(".").innerHTML = text;